name: Daily Update

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update file
        run: |
          echo "Updated on $(date)" >> log.txt
      - name: Commit
        run: |
          git config --global user.name "nammalwarsai"
          git config --global user.email "2300033899@kluniversity.in"
          git add .
          git commit -m "auto update"
          git push
